---
- hosts: localhost
  roles:
    - role: '{{ playbook_dir }}'
      vars:
        gri_archive_formats:
          pack: |
            {{- app_repo }}{{ app_separator }}{{ app.tag }}{{ app_separator }}{{ gri_os -}}
            {% if 'amd64' != gri_arch %}
            {{ app_separator }}{{ gri_arch -}}
            {% endif %}
            .{{ app_archive_extension -}}
          argo_workflows: argo-{{ gri_os }}-{{ gri_arch }}.gz
        gri_checksum_formats:
          pack: '{{ app_archive_format }}.sha256'
          argo_workflows: 'argo-workflows-cli-checksums.txt'
        gri_unarchive_binary_formats:
          argo_workflows: 'argo-{{ gri_os }}-{{ gri_arch }}'
        gri_installs:
          - repo: bradfordwagner/go-azure-blob-cli
            binary_name: abc
            tag: 1.3.0
          - repo: bradfordwagner/gh-template-go-cli
            binary_name: testcli
            tag: v1.6.0
          - repo: bradfordwagner/ks
            tag: 1.11.0
          - repo: buildpacks/pack
            archive_extension: tgz
            archive_key: pack
            checksum_key: pack
            separator: '-'
            tag: v0.34.2
          # see: https://github.com/FiloSottile/mkcert/releases
          - repo: FiloSottile/mkcert
            tag: v1.4.4
            separator: '-'
            archive_extension: ''
            unarchive_format: binary
          # https://github.com/argoproj/argo-workflows/releases
          - repo: argoproj/argo-workflows
            separator: '-'
            archive_key: argo_workflows
            checksum_key: argo_workflows
            unarchive_format: gzip
            unarchive_binary_key: argo_workflows
            binary_name: argo
            tag: v3.6.7

  tasks:
    - name: check binaries installed
      include_tasks: ./tests/check_output.yml
      loop_control:
        loop_var: item
      loop:
         - abc -h
         - ks -h
         - pack -h
         - testcli -h
         - mkcert --version
         - argo -h
